// Constants related to API endpoints
export const API_ENDPOINTS = {
  login: '/login',
  register: '/register',
  createPost: '/post',
  post:'/post',
  getPosts: '/post',
  getPostsGuest: '/get-all-posts',
  getSinglePostsGuest: '/one-post',
  showSpecificPost: '/post',
  getUserPosts: '/profile',
  UpdateUser: '/profile/update',
  UpdatePassword: '/password/update',
  likePost: 'post/like',
  follow: 'follow',
  commentPost: 'post/comment',
  deleteComment: 'delete-interaction',
  updatePost: 'post/update',
  sector: '/sector',
  deletePost: 'post/delete',
  sharePost: 'post/share',
  zone: '/zone',
  report: '/reports',
  event: '/events',
  getEvents: '/events',
  getEventsGuest: '/get-all-events',
  getSingleEventsGuest: '/one-event',
};
