// Constants related to API endpoints
export const API_ENDPOINTS = {
  login: '/login',
  register: '/register',
  createPost: '/post',
  post:'/post',
  getPosts: '/post',
  showSpecificPost: '/post',
  getUserPosts: '/profile',
  UpdateUser: '/profile/update',
  UpdatePassword: '/password/update',
  likePost: 'post/like',
  commentPost: 'post/comment',
  updatePost: 'post/update',
  sector: '/sector',
  deletePost: 'post/delete',
  sharePost: 'post/share',
  zone: '/zone',
  event: '/events',
  getEvents: '/events',
};
