name: Vue.js CI/CD Pipeline

on:
  push:
    branches:
      - deploy  # This ensures the workflow runs only when code is pushed to the 'deploy' branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Pulls your project code

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Match this with your project's node version

    - name: Install dependencies
      run: npm install  # Installs your npm dependencies

    - name: Run Linting
      run: npm run lint  # Lints your code using the eslint configuration in your project

    - name: Run Unit Tests
      run: npm run test  # Runs your tests using vitest

    - name: Build the Project
      run: npm run build  # Builds your Vue.js app

    # - name: Deploy to AWS S3
    #   uses: jakejarvis/s3-sync-action@v0.5.1  # Updated action
    #   with:
    #     args: --delete  
    #   env:
    #     AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}  # S3 bucket name
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # AWS access key
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # AWS secret key
    #     AWS_REGION: 'us-east-1'  # Your AWS region
    #     SOURCE_DIR: './dist'  # Build directory from Vite
